// Generated by Selenium IDE
package it.unisa.uniclass.testing.integration;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class AttivazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    login();
  }

  private void login() {
    driver.get("http://localhost:8080/UniClass-Dependability/Home");
    driver.findElement(By.cssSelector("span > a > img")).click();
    driver.findElement(By.id("email")).sendKeys("giannisereni@unisa.it");
    driver.findElement(By.id("password")).sendKeys("3201$wEr"); // ggignore
    driver.findElement(By.cssSelector(".logreg")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    WebElement userIcon = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("span > img")));
    userIcon.click();

    WebElement gestioneUtenti = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Gestione Utenti")));
    gestioneUtenti.click();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tC1AllValid() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.id("email")).sendKeys("s.davanzo5@studenti.unisa.it");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("success") || driver.getPageSource().contains("attivato"));
  }

  @Test
  public void tC2associazioneErrata() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.id("email")).sendKeys("s.davanzo5@studenti.unisa.it");
    WebElement dropdown = driver.findElement(By.id("tipo"));
    dropdown.findElement(By.xpath("//option[. = 'Docente']")).click();
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("errore") || driver.getPageSource().contains("associazione"));
  }

  @Test
  public void tC3mailNotPresentDB() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("non presente") || driver.getPageSource().contains("email"));
  }

  @Test
  public void tC4emailNotFormatted() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("formato") || driver.getPageSource().contains("valida"));
  }

  @Test
  public void tC5notPresentBothInfo() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    driver.findElement(By.id("matricola")).sendKeys("0512117895");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("non presente") || driver.getPageSource().contains("errore"));
  }

  @Test
  public void tC6notPresentBothAndNotFormattedEmail() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).sendKeys("0512117895");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("errore") || driver.getPageSource().contains("valida"));
  }

  @Test
  public void tC7notPresentBothNotFormattedMatricola() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    driver.findElement(By.id("matricola")).sendKeys("aaaaa?");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("matricola") || driver.getPageSource().contains("valida"));
  }

  @Test
  public void tC8nothingGood() {
    driver.get("http://localhost:8080/UniClass-Dependability/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).sendKeys("aaaaa");
    driver.findElement(By.cssSelector(".submit-btn")).click();

    assertTrue(driver.getPageSource().contains("errore") || driver.getPageSource().contains("non valido"));
  }
}
